Friend Module CharacterType
    Friend Const N00b = "N00b"
    Friend Const Blob = "Blob"
    Friend Const CellarRat = "CellarRat"
    Friend Const SewerRat = "SewerRat"
    Friend Const KingRat = "KingRat"
    Friend Const Skeleton = "Skeleton"
    Friend Const Zombie = "Zombie"
    Friend Const Goblin = "Goblin"
    Friend Const Orc = "Orc"
    Friend Const Cyclops = "Cyclops"
    Friend Const MoonPerson = "MoonPerson"
    Friend Const Mummy = "Mummy"
    Friend Const Gargoyle = "Gargoyle"
    Friend Const Guardian = "Guardian"
End Module
