Friend Module Constants
    Friend Const AbandonGameText = "Abandon Game"
    Friend Const ConsumeText = "Consume"
    Friend Const ContinueText = "Continue"
    Friend Const EquipmentText = "Equipment"
    Friend Const EquipText = "Equip"
    Friend Const FightText = "Fight"
    Friend Const GameMenuText = "Game Menu"
    Friend Const InteractText = "Interact..."
    Friend Const InventoryText = "Inventory"
    Friend Const LoadGameText = "Load Game..."
    Friend Const MainMenuText = "Main Menu"
    Friend Const MoveText = "Move..."
    Friend Const NeverMindText = "Never Mind"
    Friend Const NoText = "No"
    Friend Const OkText = "Ok"
    Friend Const PickUpText = "Pick Up..."
    Friend Const QuitText = "Quit"
    Friend Const RunText = "Run"
    Friend Const SaveGameText = "Save Game..."
    Friend Const StartText = "Start"
    Friend Const StatusText = "Status"
    Friend Const UnequipText = "Unequip"
    Friend Const UseText = "Use"
    Friend Const YesText = "Yes"
End Module
