Friend Module ItemType
    Friend Const SewerKey = "SewerKey"
    Friend Const GraveyardKey = "GraveyardKey"
    Friend Const TowerKey = "TowerKey"
    Friend Const UfoKey = "UfoKey"
    Friend Const MachineKey = "MachineKey"
    Friend Const Jools = "Jools"
    Friend Const Chikkin = "Chikkin"
    Friend Const CellarRatTail = "CellarRatTail"
    Friend Const SewerRatTail = "SewerRatTail"
    Friend Const Dagger = "Dagger"
    Friend Const Shortsword = "Shortsword"
    Friend Const Broadsword = "Broadsword"
    Friend Const Longsword = "Longsword"
    Friend Const Axe = "Axe"
    Friend Const Shield = "Shield"
    Friend Const Helmet = "Helmet"
    Friend Const LeatherArmor = ""
    Friend Const ChainMail = "ChainMail"
    Friend Const PlateMail = "PlateMail"
    Friend Const SkullFragment = "SkullFragment"
    Friend Const ZombieTaint = "ZombieTaint"
    Friend Const Feather = "Feather"
End Module
